version: '2'
services:
  web:
    build: .
    image: phims:latest
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"