local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
amazon:
  service: S3
  access_key_id: <% Rails.application.credentials[Rails.env.to_sym][:aws][:access_key_id] %>
  secret_access_key: <% Rails.application.credentials[Rails.env.to_sym][:aws][:secret_access_key] %>
  bucket: <% Rails.application.credentials[Rails.env.to_sym][:aws][:bucket] %>
  region: <% Rails.application.credentials[Rails.env.to_sym][:aws][:region] %>